"""Quantization table utilities shared by encoders."""

from __future__ import annotations

from pathlib import Path


def perturb_table(rng, table: list[list[int]], strength: float) -> list[list[int]]:
    """Perturb an 8x8 quant table by up to +/-strength fraction."""

    out: list[list[int]] = []
    for r, row in enumerate(table):
        out_row: list[int] = []
        for c, v in enumerate(row):
            hf = (r + c) / 14.0
            local = strength * (0.35 + 0.65 * hf)
            delta = rng.uniform(-local, local)
            nv = int(round(v * (1.0 + delta)))
            out_row.append(max(1, min(255, nv)))
        out.append(out_row)
    return out


def perturb_steps(rng, steps: list[int], strength: float) -> list[int]:
    """Perturb flat 8x8 quant steps by up to +/-strength fraction."""

    out: list[int] = []
    for i, v in enumerate(steps):
        hf = i / 63.0
        local = strength * (0.35 + 0.65 * hf)
        nv = int(round(v * (1.0 + rng.uniform(-local, local))))
        out.append(max(1, min(255, nv)))
    return out


def write_qtables_file(path: Path, luma: list[list[int]], chroma: list[list[int]]) -> None:
    """Write cjpeg-style -qtables file."""

    lines: list[str] = ["# qtables generated by jpeg_variety (rare custom tables)"]
    for row in luma:
        lines.append(" ".join(str(x) for x in row))
    lines.append("")
    for row in chroma:
        lines.append(" ".join(str(x) for x in row))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_qtf_file(path: Path, luma_steps: list[int], chroma_steps: list[int]) -> None:
    """Write JPEG reference encoder -qtf file."""

    all_steps = luma_steps + chroma_steps
    txt = "\n".join(str(int(x)) for x in all_steps) + "\n"
    path.write_text(txt, encoding="utf-8")
